### ISSUE TITLE
state circuit for log/receipt RW table section

### ISSUE THREAD

**Issue by DreamWuGit** [appliedzkp/zkevm-specs#141]
As @ed255 and @CPerezz mentioned in pr [discussion](https://github.com/appliedzkp/zkevm-specs/pull/125#discussion_r823794931) ,  we requires `TxLog` section constraint in state circuit ,  need  more discussion and detail design for that part !

**Comment by CPerezz** [comment]
A few concerns/ideas arised from this.
It will be nice to wait until @han0110 is back to resume this. But of course we can trigger the discussion.

I thought about several things.
1) Force bus-mapping to treat logs as another StorageOp and allow for a much easier construction of the storage checks for the generated/reverted logs (Even reversion will work differently here as no state is changed at any point for the logs). Then the circuit will check the operations generated for each step and will expect that for LOG opcode, we need to have log operations in the table. As we do with storage but in a slightly simple manner (no deletion, no reversion etc..).
2) We can define for the BlockContext an Optional field which contains any logs generated for the Block.
With this we can build a table/edit the `rw_table` to include LogHash/ID -> (Step of creation, contents) or something similar.
Allowing us to lookup in the `block_context table` or `rw_table` the info related to the log.

1. Is quite complex and expensive probably.
2. Is much more simpler and seems to come at a cost of 1 extra lookup from the context table.

Please, let me know if this does not make sense.

**Comment by CPerezz** [comment]
cc @barryWhiteHat

**Comment by han0110** [comment]
For whether to track `log_index` in `StepState` or not, I think we don't need to as Edu mentioned in https://github.com/appliedzkp/zkevm-specs/pull/125#discussion_r821592254 [^log-index-auto-increment]. And the `log_index` as "index of log in receipt" instead of "in the whole block" makes more sense to me, also we might want `log_length` and `data_length` to be recorded for rlp encoding and `bloom` calculation.

[^log-index-auto-increment]: Reset `log_index` when `tx_id` increases, increase `log_index` when `tag` changes to `Address`, make sure `tag` can only increase when `log_index` stays same, make sure `topic_index` and `data_index` can only increase when `tag` stays same.

For whether to revert log or not, it seems no reversion on log would make thing easier, we only write it when `is_persistent` as Edu mentioned in https://github.com/appliedzkp/zkevm-specs/pull/125#pullrequestreview-902885723.

Also it seems `tx_id` is missing in the lookup in #125 (otherwise we don't know which tx the log belongs to), and we could just extend the tag `TxLog` to be `TxReceipt` to take `is_tx_success` and `cumulative_gas_used` into consideration (`bloom` could be calculated in another specific layouted circuit), then all the information of receipt trie are in State circuit.

**Comment by DreamWuGit** [comment]
@han0110  evm  `log_index ` [raw definition](https://github.com/ethereum/go-ethereum/blob/master/core/types/log.go#L50L51) represents index of the block,  as one receipt can hold a set of logs,  index of receipt can not identify definite log entry.    since  `log_index `(BTW, renamed to `log_id` now) can located each log entry, so removed the `tx_id` before.      

> bloom could be calculated in another specific layouted circuit
you mean bloom function will import new circuit which outside the RW table(state circuit )?

**Comment by han0110** [comment]
> evm log_index [raw definition](https://github.com/ethereum/go-ethereum/blob/master/core/types/log.go#L50L51) represents index of the block

I think that field is for higher level usage, in receipt RLP encoding, such information is not encoded [^receipt-definition], so in my mind we don't actually need to record that. I couldn't find how to infer the `tx_id` by `log_id` in #125, would you like to elaborate more on this? Because when we are building the receipt trie, we need to know which specific tx the log belongs to.

> you mean bloom function will import new circuit outside the RW table(state circuit )?

I think so, it might require some specific layout to efficiently calculate it. But in our context, it seems not so useful, so I would say we leave it unchecked for now and implement it in the future.

[^receipt-definition]: https://ethereum.github.io/yellowpaper/paper.pdf _(22) - (27)_

**Comment by DreamWuGit** [comment]
after chat with @han0110 in tg ,  we agree to  revisit & defer these consideration change  to future PR of  log state circuit/receipt tree circuit,  thanks!

**Comment by DreamWuGit** [comment]
draft some ideas regarding state circuit part [here](https://hackmd.io/7iI0736UToO-w01RKxEevw?view) ， some need more classification, nice to see your comments!

**Comment by DreamWuGit** [comment]
@CPerezz  replied your comment , @han0110 @ed255  @ChihChengLiang  could you please also have a look ?

**Comment by DreamWuGit** [comment]
closing by #159  merged
